# Generated by Django 4.2.4 on 2023-08-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('CBDOil', 'CBD Oil'), ('CBDPaste', 'CBD Paste'), ('CBDDABWAX', 'CBD DAB WAX'), ('CBDVape', 'CBD Vape'), ('CBDCosmetics', 'CBD Cosmetics')], max_length=13)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
