# Generated by Django 4.2.4 on 2023-08-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CBD Oil', 'CBD Oil'), ('CBD Paste', 'CBD Paste'), ('CBD DAB WAX', 'CBD DAB WAX'), ('CBD Vape', 'CBD Vape'), ('CBD Cosmetics', 'CBD Cosmetics')], max_length=13),
        ),
    ]
