# Generated by Django 4.2.4 on 2023-08-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CBDOil', 'CBD Oil'), ('CBDPaste', 'CBD Paste'), ('CBDDABWAX', 'CBD DAB WAX'), ('CBDVape', 'CBD Vape'), ('CBDCosmetics', 'CBD Cosmetics')], max_length=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
